---
# Risorse utili per le CTF (la dashboard è per i tool locali; qui solo link).

- Risorse:
    - CTFtime:
        - abbr: CT
          href: https://ctftime.org/
    - HackTricks:
        - abbr: HT
          href: https://book.hacktricks.xyz/
    - picoCTF:
        - abbr: pC
          href: https://picoctf.org/
    - Writeups (susers):
        - abbr: WU
          href: https://github.com/susers/Writeups
    - SekaiCTF:
        - abbr: SK
          href: https://github.com/project-sekai-ctf
    - CTF dockerfiles (SniperOJ):
        - abbr: SJ
          href: https://github.com/SniperOJ/Jeopardy-Dockerfiles
    - RTB CTF Framework:
        - abbr: RB
          href: https://github.com/abs0lut3pwn4g3/RTB-CTF-Framework
    - RevShells:
        - abbr: RS
          href: https://www.revshells.com/
